### PR TITLE
Multiple crumbs

### PR DESCRIPTION
**Pull request by aexmachina**
This PR adds the ability for a controller to provide a number of breadcrumbs.

Be aware that this PR includes the changes in the ember-cli branch.

### CODE REVIEW

**Comment by aexmachina** [comment]
I've updated this PR with my changes moved into the JavaScript.

**Comment by aexmachina** [comment]
> Regarding multiple crumbs per controller, I think there is a reasonable need for this. I'm not sure what the best API to accomplish this is quite yet.

I'm using this API in our code and it works very well:

```js
  breadCrumbs: function() {
    var lists = this.get('model');
    var lists = [list].concat(list.get('parents'));
    return lists.map(list => ({
      label: list.get('name'),
      model: list
    })).reverse();
  }.property('model'),
```

> I'd like to make sure that, however it gets implemented, it's hard for users to add multiple crumbs in a way that would break live-updating via bindings. I'll think about this a bit.

There's definitely no issues with breaking bindings in this implementation.

**Comment by aexmachina** [comment]
I just noticed #10, and should point out that this becomes easy if we support `breadCrumbs` containing objects rather than just strings.

**Comment by aexmachina** [comment]
Hi there, what's the status on this PR? We're using this in our app and it's working very nicely. Would be good to get this merged in, and I'm sure we're not the only people who will need this feature. I'd be happy to change `crumb.label` back to `crumb.name` if you like, and we can add backwards-compatibility as well if you think it's necessary although it's pretty trivial to upgrade `breadCrumb: {}` to `breadCrumbs: [{}]`.

Let me know your thoughts :)

**Comment by chrisfarber** [comment]
Hey, sorry for the delay responding – I'm out of town for a funeral.

I agree that this is a commonly desired feature and needs to get merged in. I'd been hoping wrap the component in some system tests before adding new features, but it's probably best to go ahead and get this supported.

I would like to see some compatibility for specifying only one crumb without need for an array. This will allow the common case to make use of computed property helpers and be a bit cleaner aesthetically.

**Comment by aexmachina** [comment]
Okay cool, I've added that. Another thing that we've needed is the ability to provide the model for the transition. I haven't updated the README because my feeling is that we should document the `breadCrumbs: [{label: 'Foo'}]` rather than the `breadCrumb: 'Foo'` usage because it's the usage that provides support for all the features (multiple crumbs, specifying path, `model` and `linkable`) but it's really your call.

**Comment by chrisfarber** [comment]
I appreciate your help! I'll get that merged in soon and cut a release.

**Pull request merged**
